
services:
  rabbitmq:
    image: rabbitmq:4.0-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: go-u
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persiste dados do RabbitMQ
  gosend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:3
    ports:
      - "9000:8000"
    volumes:
      - .:/app                 
      - /app/vendor            # Exclui a pasta de dependências (opcional)
    working_dir: /app 
    command: "go run -mod=vendor cmd/send.go" # Uso ao desenvolver
    depends_on:
      - rabbitmq
    environment:
      GO_ENV: development 
  goreceiver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:3
    ports:
      - "8000:8000"
    volumes:
      - .:/app                 
      - /app/vendor            # Exclui a pasta de dependências (opcional)
    working_dir: /app 
    command: "go run -mod=vendor cmd/receive.go" # Uso ao desenvolver
    depends_on:
      - rabbitmq
    environment:
      GO_ENV: development 

volumes:
  rabbitmq_data:
    driver: local